# This is a basic workflow to help you get started with Actions

name: Deploy to Digital Ocean

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean
        run: |
          # Clone the repo to the server if it doesn't exist yet
          ssh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} '[ -d ~/portfolio ] || git clone https://github.com/eshasherry/portfolio.git ~/portfolio'
          
          # Pull latest changes and rebuild
          ssh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} '
            cd ~/application/portfolio
            git pull
            cd ..
            # Stop the container first to avoid the ContainerConfig error
            docker-compose stop portfolio
            
            # Remove the container to ensure clean recreation
            docker-compose rm -f portfolio
            
            # Rebuild the image
            docker-compose build portfolio
            
            # Start just the portfolio service
            docker-compose up -d portfolio
            
            # Check if container is running
            sleep 5
            if docker ps | grep portfolio; then
              echo "Portfolio container successfully deployed"
            else
              echo "Portfolio container failed to start, checking logs:"
              docker-compose logs portfolio
              exit 1
            fi
          '
    
